
include Makefile.inc

.PHONY: clean distclean lib error conf doc

main: main.c lib
	${CC} ${CFLAGS} main.c -Isrc -Lsrc ${LFLAGS} -lmbn -o main

lib: force_look
	${MAKE} -C src/

clean:
	${MAKE} -C src/ clean
	${MAKE} -C doc/ clean
	rm -f main

distclean: clean
	rm Makefile.inc

Makefile.inc: Makefile.inc.in
	@cp Makefile.inc.in Makefile.inc
	@if [ "`uname`" = 'Linux' ]; then\
	  echo "Detected target: linux";\
	else\
	  echo "Detected target: mingw";\
	  sed s/PLATFORM=linux/PLATFORM=mingw/ Makefile.inc.in > Makefile.inc;\
	fi
	@echo "Autogenerated Makefile.inc, you may want to make some modifications"
	@${MAKE} error

error:
	${error Please review Makefile.inc}

conf: Makefile.inc

doc:
	${MAKE} -C doc/

force_look:

